# Generated by Django 2.2.5 on 2020-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_agelife_groupname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=100)),
                ('datetime', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
